### ISSUE TITLE
RemoveSelf / RemoveFromParent(this)

### ISSUE THREAD

**Issue by NuclearCookie** [GlenDC/StarEngine#45]
Would be a nice extra feature. Now you have to do GetParent()->RemoveChild(this)

**Comment by GlenDC** [comment]
Object has the Destroy() function, before it didn't take into account that an object could also be a child of another object. So now when you call it, it will function correctly. That means that if it has a parent, it will delete itself from the parent, otherwise it will be deleted from the scene. Note that it will also delete the object itself.
